[program:drena-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/drena-app/artisan queue:work database --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/www/drena-app/storage/logs/worker.log
stopwaitsecs=3600

[program:drena-schedule]
process_name=%(program_name)s
command=/bin/bash -c "while true; do cd /var/www/drena-app && php artisan schedule:run --verbose --no-interaction >> /dev/null 2>&1; sleep 60; done"
autostart=true
autorestart=true
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/drena-app/storage/logs/schedule.log
